"""score was delete from game api

Revision ID: 2654c1958128
Revises: ac2c1c6a5848
Create Date: 2025-04-12 19:30:37.134951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2654c1958128'
down_revision: Union[str, None] = 'ac2c1c6a5848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_questions', sa.Column('score', sa.Integer(), nullable=False))
    op.drop_column('games', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('game_questions', 'score')
    # ### end Alembic commands ###
